### ISSUE TITLE
Unprocessed TODO Items

### ISSUE THREAD

**Issue by acbart** [pedal-edu/pedal#51]
These are stolen from various parts of the codebase and deposited here, to be process and turned into Issues.

- [x] TODO: Statistics
- [x] TODO: Output checking for folder of submissions
- [x] TODO: Handle tabular output for unit tests
- [ ] TODO: Big annotated example
- [ ] TODO: Fix sections example
- [ ] TODO: Set up "Unit Test" environment
- [ ] TODO: Add documentation for each one, particularly toolkit
- [ ] TODO: Set up command line and other environments
- [ ] TODO: Improve feedback tracking for all the tools
- [ ] TODO: Fix up imports everywhere to be consistent, particularly for the modules themselves
- [ ] TODO: A/B Tool - override existing feedback, and tools for randomly or deterministically choosing students

**Comment by acbart** [comment]
These are all things from before the last major rewrite. There are better, separate issues for each one, I believe.
